services:
  - type: web
    name: puppeteer-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node scraper.js
    envVars:
      - key: API_KEY
        value: "mySuperSecretKey123"
